
#define HAVE_STDINT_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDLIB_H 1
#define NEED_SYS_TYPES_H 1

#define HAVE_DECL_ROUND 1

//#define HAVE_STRSIGNAL 

#define RETSIGTYPE void

#define HAVE_ZLIB_H 1

#define HAVE_LINUX_VIDEODEV_H 1
#define HAVE_LINUX_VIDEODEV2_H 1

#define HAVE_LIBAVCODEC 1
#define HAVE_LIBAVUTIL_AVUTIL_H 1
#define HAVE_LIBAVCODEC_AVCODEC_H 1
#define HAVE_LIBAVFORMAT_AVFORMAT_H 1

#define HAVE_LIBSWSCALE 1
#define HAVE_LIBSWSCALE_SWSCALE_H 1

